name: Quality assurance PHP

on:
    push:
        paths:
            - '**workflows/php-qa.yml'
            - '**.php'
            - '**phpcs.xml.dist'
            - '**phpstan.neon.dist'
            - '**composer.json'
    pull_request:
        paths:
            - '**workflows/php-qa.yml'
            - '**.php'
            - '**phpcs.xml.dist'
            - '**phpstan.neon.dist'
            - '**composer.json'
    workflow_dispatch:
        inputs:
            jobs:
                required: true
                type: choice
                default: 'Run all'
                description: 'Choose jobs to run'
                options:
                    - 'Run all'
                    - 'Run PHPCS only'
                    - 'Run PHPStan only'
                    - 'Run lint only'

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    lint:
        if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run all') || (github.event.inputs.jobs == 'Run lint only')) }}
        uses: inpsyde/reusable-workflows/.github/workflows/lint-php.yml@main
        strategy:
            matrix:
                php: [ '7.4', '8.0', '8.1', '8.2', '8.3', '8.4' ]
        with:
            PHP_VERSION: ${{ matrix.php }}
            LINT_ARGS: '-e php --colors --show-deprecated ./src'

    coding-standards-analysis:
        if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run all') || (github.event.inputs.jobs == 'Run PHPCS only')) }}
        uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main
        with:
            PHP_VERSION: '8.3'

    static-code-analysis:
        if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run all') || (github.event.inputs.jobs == 'Run PHPStan only')) }}
        uses: inpsyde/reusable-workflows/.github/workflows/static-analysis-php.yml@main
        strategy:
            matrix:
                php: [ '8.1', '8.2', '8.3', '8.4' ]
                include:
                    - php: '7.4'
                      composer: '--ignore-platform-req=php'
                    - php: '8.0'
                      composer: '--ignore-platform-req=php'
        with:
            PHP_VERSION: ${{ matrix.php }}
            COMPOSER_ARGS: ${{ matrix.composer || '' }}
